language: c
compiler:
  - clang
  - gcc
install:
  - wget "https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip"
  - unzip -q ninja-linux.zip -d build
  - export PATH="$PWD/build:$PATH"
  - pip install meson
script:
  - meson build
  - ninja -C build test
